version: '3.1'

services:

  db:
    image: mysql:8.0.30
    container_name: mysql8
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Jiuyukeji!@#123
      TZ: Asia/Shanghai
    ports:
      - 3306:3306
    volumes:
      - /home/ecs-user/mysql/data:/var/lib/mysql
      - /home/ecs-user/mysql/conf:/etc/mysql/conf.d

  # python3:
  #   image: python:slim
  #   container_name: python3
  #   restart: always
  #   stdin_open: true
  #   tty: true
  #   expose:
  #     - "22"

  memcached:
    image: memcached:1.6
    container_name: memcached
    restart: always

  web:
    build:
      context: .
      dockerfile: php-apache.dockerfile
    image: php-apache
    container_name: php-apache
    depends_on:
      - db
      - memcached
      # - python3
    links:
      - db
      # - python3
      - memcached
    restart: always
    ports:
      - 80:80
    volumes:
      - /var/www/website:/var/www/html
      - /home/ecs-user/php-apache/apache2:/etc/apache2
