version: '3'
services:
  nginx:
    restart: always
    container_name: nginx_local
    image: nginx
    ports:
      - 80:80
    network_mode: bridge
    volumes:
      - ./html:/usr/share/nginx/html
      - ./logs:/var/log/nginx
      - ./conf:/etc/nginx/conf.d
    environment:
      - NGINX_PORT=80
    privileged: true
