version: '3.1'

services:
  # https://hub.docker.com/_/mysql
  db:
    image: mysql:8.0.30
    container_name: mysql8
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Jiuyukeji!@#123
      TZ: Asia/Shanghai
    ports:
      - 3306:3306
    volumes:
      - /home/ecs-user/mysql/data:/var/lib/mysql
      - /home/ecs-user/mysql/conf:/etc/mysql/conf.d

  # https://hub.docker.com/_/memcached
  memcached:
    image: memcached:1.6
    container_name: memcached
    restart: always

  # https://hub.docker.com/_/php
  web:
    build:
      context: .
      dockerfile: php-apache.dockerfile
    image: php-apache
    container_name: php-apache
    depends_on:
      - db
      - memcached
    links:
      - db
      - memcached
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/www/website:/var/www/html
      - /var/log/apache2/:/var/log/apache2/
      - /home/ecs-user/php-apache/apache2:/etc/apache2
